"""Solver strategies: modes A, B, and C."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from math import log2

from wordle.constants import MAX_TURNS, WORD_LENGTH
from wordle.engine import score_guess
from wordle.solver.constraints import SolverConstraints

# ── Mode C precomputed constants ───────────────────────────────────────────────
# opener: best avg-turns word — 3.4331 avg turns (5.7427 bits entropy, optimal letter coverage).
MODE_C_OPENER = "crate"

# turn-2 lookup: maps opener pattern-int → best turn-2 word from full guess pool.
# Pattern int = sum(score[i] * 3^i for i in 0..4).
# Generated by scripts/precompute_mode_c.py.
MODE_C_TURN2: dict[int, str] = {
    0: 'soily',
    1: 'pulis',
    2: 'ulmin',
    3: 'durrs',
    4: 'locum',
    5: 'ivory',
    6: 'gipon',
    7: 'brick',
    8: 'psion',
    9: 'sonly',
    10: 'limbo',
    11: 'nobly',
    12: 'lorry',
    13: 'scram',
    14: 'cargo',
    15: 'arbor',
    17: 'croak',
    18: 'slink',
    19: 'plush',
    20: 'khans',
    21: 'dhows',
    22: 'scarf',
    23: 'chard',
    24: 'dings',
    25: 'wrack',
    26: 'lynch',
    27: 'hoist',
    28: 'pouch',
    29: 'clout',
    30: 'shout',
    31: 'torch',
    32: 'court',
    33: 'tonus',
    34: 'trick',
    35: 'crust',
    36: 'talon',
    37: 'haply',
    38: 'caput',
    39: 'satyr',
    40: 'actor',
    41: 'carat',
    42: 'triad',
    45: 'slink',
    46: 'scant',
    47: 'chant',
    48: 'skimp',
    50: 'chart',
    51: 'fling',
    52: 'track',
    53: 'craft',
    54: 'noisy',
    56: 'cloth',
    57: 'fight',
    60: 'broth',
    63: 'spiny',
    65: 'cacti',
    66: 'party',
    72: 'loath',
    78: 'wrath',
    81: 'wedel',
    82: 'bedel',
    83: 'liken',
    84: 'lines',
    85: 'dicey',
    86: 'dowry',
    87: 'defer',
    88: 'wreck',
    89: 'plied',
    90: 'kneel',
    91: 'decal',
    92: 'camel',
    93: 'palms',
    94: 'racer',
    95: 'cedar',
    96: 'bread',
    98: 'creak',
    99: 'child',
    100: 'abled',
    102: 'badly',
    103: 'reach',
    108: 'sleet',
    109: 'eject',
    110: 'bevel',
    111: 'meter',
    112: 'recut',
    114: 'truer',
    115: 'erect',
    116: 'crept',
    117: 'smelt',
    118: 'eclat',
    119: 'cheat',
    120: 'tweel',
    122: 'cater',
    123: 'great',
    126: 'newly',
    127: 'enact',
    129: 'heart',
    130: 'react',
    135: 'plesh',
    138: 'berth',
    144: 'delta',
    147: 'earth',
    153: 'death',
    162: 'sling',
    163: 'dinos',
    164: 'honds',
    165: 'sprog',
    166: 'force',
    167: 'curse',
    168: 'ponds',
    169: 'price',
    170: 'admin',
    171: 'mails',
    172: 'dance',
    173: 'abhor',
    174: 'align',
    175: 'farce',
    176: 'carve',
    177: 'arise',
    180: 'slump',
    181: 'peace',
    182: 'cease',
    183: 'align',
    184: 'scare',
    186: 'kedge',
    187: 'brace',
    188: 'anvil',
    189: 'shily',
    190: 'twice',
    191: 'cutie',
    192: 'store',
    195: 'tripe',
    196: 'trice',
    198: 'bathe',
    207: 'gleek',
    210: 'stare',
    213: 'trade',
    214: 'trace',
    216: 'muils',
    218: 'chute',
    219: 'forte',
    222: 'write',
    225: 'whups',
    226: 'acute',
    227: 'caste',
    234: 'glops',
    240: 'grate',
    242: 'crate',
}


# turn-3 lookup: maps (opener_pattern, turn2_pattern) → best turn-3 word.
# Generated by scripts/precompute_mode_c_t3.py.
MODE_C_TURN3: dict[tuple[int, int], str] = {
    (0, 2): 'skunk',
    (0, 3): 'aglow',
    (0, 5): 'shown',
    (0, 6): 'bumph',
    (0, 7): 'bonus',
    (0, 9): 'humid',
    (0, 11): 'squib',
    (0, 12): 'bingo',
    (0, 13): 'bison',
    (0, 19): 'using',
    (0, 20): 'flown',
    (0, 21): 'onion',
    (0, 24): 'doing',
    (0, 27): 'flung',
    (0, 28): 'bleep',
    (0, 29): 'among',
    (0, 30): 'blond',
    (0, 31): 'floss',
    (0, 32): 'sloop',
    (0, 36): 'lipid',
    (0, 39): 'igloo',
    (0, 42): 'folio',
    (0, 45): 'blind',
    (0, 47): 'sling',
    (0, 56): 'skulk',
    (0, 72): 'build',
    (0, 74): 'skill',
    (0, 99): 'dying',
    (0, 108): 'glyph',
    (0, 162): 'dumpy',
    (0, 163): 'hokum',
    (0, 167): 'showy',
    (0, 168): 'goody',
    (0, 169): 'bossy',
    (0, 171): 'dwang',
    (0, 172): 'gipsy',
    (0, 180): 'unify',
    (0, 182): 'shiny',
    (0, 189): 'bulky',
    (0, 195): 'lobby',
    (0, 198): 'filmy',
    (0, 216): 'badge',
    (0, 218): 'shyly',
    (0, 222): 'dwang',
    (0, 225): 'width',
    (1, 6): 'balmy',
    (1, 9): 'block',
    (1, 15): 'lucky',
    (1, 24): 'gulch',
    (1, 27): 'finch',
    (1, 29): 'picky',
    (1, 33): 'juicy',
    (1, 36): 'flick',
    (1, 54): 'ionic',
    (1, 81): 'shock',
    (1, 84): 'shuck',
    (1, 90): 'scold',
    (1, 108): 'disco',
    (2, 1): 'chuck',
    (2, 7): 'cloud',
    (2, 30): 'child',
    (2, 33): 'click',
    (2, 81): 'conch',
    (2, 114): 'cling',
    (2, 135): 'conic',
    (3, 9): 'honor',
    (3, 10): 'rigid',
    (3, 12): 'flour',
    (3, 15): 'humor',
    (3, 18): 'horny',
    (3, 19): 'wordy',
    (3, 24): 'burly',
    (3, 51): 'furor',
    (3, 54): 'glory',
    (3, 55): 'fjord',
    (3, 57): 'blurb',
    (3, 72): 'lorry',
    (3, 78): 'furry',
    (3, 90): 'risky',
    (3, 102): 'shrub',
    (3, 135): 'shirk',
    (3, 138): 'slurp',
    (6, 0): 'dryly',
    (6, 3): 'frisk',
    (6, 5): 'grill',
    (6, 12): 'prism',
    (6, 27): 'droll',
    (6, 29): 'gross',
    (6, 36): 'proud',
    (6, 54): 'amend',
    (6, 63): 'droop',
    (6, 84): 'brink',
    (6, 85): 'bring',
    (6, 189): 'brown',
    (8, 27): 'crock',
    (9, 0): 'gamma',
    (9, 1): 'amiss',
    (9, 2): 'sigma',
    (9, 3): 'audio',
    (9, 6): 'dogma',
    (9, 9): 'aging',
    (9, 12): 'among',
    (9, 15): 'nomad',
    (9, 18): 'manga',
    (9, 21): 'banjo',
    (9, 27): 'axial',
    (9, 28): 'basal',
    (9, 29): 'salad',
    (9, 30): 'allow',
    (9, 32): 'salvo',
    (9, 33): 'modal',
    (9, 36): 'align',
    (9, 45): 'banal',
    (9, 162): 'pudgy',
    (9, 163): 'assay',
    (9, 164): 'sappy',
    (9, 180): 'defog',
    (9, 189): 'allay',
    (9, 216): 'midge',
    (9, 218): 'sadly',
    (10, 0): 'fancy',
    (10, 12): 'magic',
    (10, 82): 'focal',
    (11, 6): 'cocoa',
    (11, 163): 'candy',
    (12, 9): 'redub',
    (12, 10): 'ralph',
    (12, 12): 'savin',
    (12, 16): 'molar',
    (12, 18): 'karma',
    (12, 19): 'mural',
    (12, 21): 'apron',
    (12, 57): 'adorn',
    (12, 93): 'mayor',
    (12, 171): 'rainy',
    (12, 180): 'hardy',
    (12, 216): 'ahead',
    (12, 234): 'harry',
    (15, 34): 'groan',
    (15, 224): 'ardor',
    (18, 0): 'foamy',
    (18, 1): 'amass',
    (18, 2): 'smash',
    (18, 3): 'loamy',
    (18, 5): 'shall',
    (18, 6): 'llama',
    (18, 7): 'flash',
    (18, 12): 'avail',
    (18, 15): 'flail',
    (18, 60): 'bland',
    (18, 218): 'shank',
    (18, 222): 'blank',
    (19, 0): 'aback',
    (19, 6): 'black',
    (19, 27): 'smack',
    (19, 30): 'scald',
    (20, 18): 'claim',
    (20, 24): 'chaff',
    (21, 0): 'alarm',
    (21, 81): 'snarl',
    (21, 87): 'shark',
    (24, 0): 'bravo',
    (24, 2): 'drama',
    (24, 9): 'prank',
    (24, 11): 'drank',
    (24, 27): 'graph',
    (26, 27): 'cramp',
    (27, 82): 'thumb',
    (27, 84): 'outdo',
    (27, 90): 'timid',
    (27, 96): 'motif',
    (27, 100): 'thigh',
    (27, 108): 'funky',
    (27, 111): 'amply',
    (27, 126): 'align',
    (27, 168): 'donut',
    (27, 171): 'limit',
    (27, 172): 'flown',
    (27, 174): 'pilot',
    (27, 180): 'begun',
    (27, 186): 'joint',
    (27, 192): 'snout',
    (27, 193): 'shoot',
    (27, 198): 'split',
    (27, 207): 'stilt',
    (27, 222): 'boost',
    (27, 240): 'foist',
    (28, 33): 'tonic',
    (28, 36): 'tunic',
    (28, 216): 'ditch',
    (28, 222): 'botch',
    (28, 225): 'butch',
    (30, 90): 'motor',
    (30, 96): 'throb',
    (30, 101): 'stork',
    (30, 117): 'tumor',
    (30, 182): 'snort',
    (30, 189): 'blurt',
    (33, 4): 'droit',
    (33, 5): 'troll',
    (33, 29): 'truly',
    (33, 37): 'brunt',
    (36, 4): 'admit',
    (36, 7): 'waist',
    (36, 8): 'tabby',
    (36, 13): 'adult',
    (36, 14): 'tidal',
    (36, 16): 'fatal',
    (36, 31): 'about',
    (36, 32): 'today',
    (36, 40): 'begat',
    (36, 58): 'abbot',
    (36, 88): 'vughs',
    (36, 89): 'taint',
    (37, 3): 'antic',
    (37, 7): 'batch',
    (39, 95): 'strap',
    (45, 1): 'boast',
    (45, 2): 'shaft',
    (45, 5): 'shalt',
    (51, 0): 'tramp',
    (54, 3): 'photo',
    (54, 6): 'booth',
    (54, 9): 'fifth',
    (54, 30): 'gusto',
    (54, 33): 'sooth',
    (54, 168): 'booty',
    (54, 171): 'bawdy',
    (54, 189): 'dimly',
    (57, 108): 'north',
    (57, 114): 'birth',
    (63, 0): 'quota',
    (63, 162): 'batty',
    (63, 163): 'hasty',
    (81, 3): 'eking',
    (81, 6): 'bison',
    (81, 12): 'edify',
    (81, 15): 'deign',
    (81, 33): 'beefy',
    (81, 42): 'needy',
    (81, 54): 'bingo',
    (81, 56): 'woken',
    (81, 57): 'queen',
    (81, 60): 'semen',
    (81, 63): 'spied',
    (81, 66): 'kneed',
    (81, 72): 'index',
    (81, 84): 'bless',
    (81, 87): 'limbo',
    (81, 88): 'below',
    (81, 93): 'field',
    (81, 135): 'liken',
    (81, 138): 'bleep',
    (81, 165): 'champ',
    (81, 216): 'bison',
    (81, 217): 'bowel',
    (81, 219): 'expel',
    (81, 222): 'bevel',
    (82, 3): 'epoch',
    (82, 6): 'gecko',
    (84, 27): 'jembe',
    (84, 29): 'leery',
    (84, 36): 'heron',
    (84, 54): 'rowdy',
    (84, 55): 'bleed',
    (84, 56): 'lever',
    (84, 58): 'flier',
    (84, 60): 'raved',
    (84, 63): 'never',
    (84, 72): 'goner',
    (84, 78): 'diner',
    (84, 108): 'serum',
    (84, 135): 'whoop',
    (84, 141): 'miser',
    (84, 150): 'risen',
    (86, 33): 'corer',
    (87, 138): 'green',
    (87, 139): 'breed',
    (87, 144): 'brief',
    (87, 218): 'drier',
    (90, 9): 'essay',
    (90, 12): 'began',
    (90, 18): 'ahead',
    (90, 21): 'amend',
    (90, 54): 'abbey',
    (90, 57): 'ashen',
    (90, 90): 'delay',
    (90, 99): 'gleam',
    (90, 135): 'abled',
    (90, 138): 'alien',
    (90, 171): 'medal',
    (90, 216): 'bough',
    (90, 219): 'navel',
    (93, 3): 'debar',
    (93, 4): 'opera',
    (93, 6): 'gawky',
    (93, 8): 'paper',
    (93, 12): 'regal',
    (93, 15): 'early',
    (93, 21): 'relax',
    (93, 33): 'gamer',
    (93, 84): 'shear',
    (93, 87): 'safer',
    (96, 78): 'freak',
    (99, 27): 'leafy',
    (102, 30): 'learn',
    (108, 90): 'fetid',
    (108, 91): 'ethos',
    (108, 135): 'often',
    (108, 138): 'hotel',
    (108, 155): 'steed',
    (108, 171): 'befit',
    (108, 172): 'exist',
    (108, 180): 'inept',
    (108, 181): 'guest',
    (108, 182): 'spent',
    (108, 183): 'dwelt',
    (108, 185): 'smelt',
    (108, 216): 'duvet',
    (108, 217): 'onset',
    (108, 219): 'filet',
    (108, 225): 'beget',
    (108, 236): 'sheet',
    (109, 218): 'edict',
    (111, 93): 'inert',
    (111, 96): 'rebut',
    (111, 105): 'retro',
    (111, 144): 'rivet',
    (111, 150): 'beret',
    (111, 225): 'abhor',
    (111, 228): 'ether',
    (111, 234): 'otter',
    (111, 237): 'enter',
    (117, 90): 'eaten',
    (117, 101): 'stead',
    (117, 117): 'fetal',
    (117, 180): 'adept',
    (117, 207): 'bleat',
    (120, 55): 'after',
    (120, 56): 'taker',
    (120, 136): 'alter',
    (126, 6): 'beast',
    (126, 33): 'leapt',
    (135, 9): 'deity',
    (135, 36): 'testy',
    (162, 0): 'about',
    (162, 1): 'bosom',
    (162, 2): 'smoke',
    (162, 3): 'abled',
    (162, 4): 'loose',
    (162, 6): 'dumpy',
    (162, 9): 'movie',
    (162, 12): 'belie',
    (162, 20): 'seize',
    (162, 21): 'exile',
    (162, 24): 'elide',
    (162, 26): 'slide',
    (162, 27): 'undue',
    (162, 28): 'dense',
    (162, 47): 'snide',
    (162, 54): 'ozone',
    (162, 72): 'opine',
    (162, 74): 'shine',
    (162, 81): 'bough',
    (162, 82): 'geese',
    (162, 84): 'ledge',
    (162, 87): 'globe',
    (162, 93): 'bilge',
    (162, 108): 'gnome',
    (162, 117): 'binge',
    (163, 15): 'niche',
    (163, 18): 'fence',
    (163, 24): 'mince',
    (163, 84): 'slice',
    (165, 9): 'where',
    (165, 10): 'reuse',
    (165, 18): 'nerve',
    (165, 19): 'nurse',
    (165, 38): 'shore',
    (165, 45): 'borne',
    (165, 46): 'horse',
    (165, 90): 'genre',
    (165, 99): 'merge',
    (165, 117): 'rogue',
    (165, 126): 'forge',
    (168, 0): 'bribe',
    (168, 2): 'prime',
    (168, 3): 'broke',
    (168, 5): 'probe',
    (168, 9): 'brine',
    (168, 56): 'pride',
    (171, 3): 'abode',
    (171, 6): 'gauge',
    (171, 8): 'mange',
    (171, 24): 'naive',
    (171, 30): 'algae',
    (171, 33): 'halve',
    (171, 48): 'alike',
    (171, 57): 'angle',
    (171, 58): 'amble',
    (171, 60): 'eagle',
    (171, 114): 'false',
    (174, 2): 'adore',
    (180, 0): 'windy',
    (180, 2): 'drank',
    (180, 3): 'leave',
    (180, 6): 'badge',
    (180, 27): 'amaze',
    (180, 60): 'blame',
    (180, 83): 'shape',
    (183, 1): 'share',
    (183, 7): 'blare',
    (186, 162): 'brave',
    (186, 189): 'grape',
    (189, 0): 'etude',
    (189, 2): 'stoke',
    (189, 7): 'these',
    (216, 6): 'butte',
    (225, 81): 'baste',
    (234, 81): 'skate',
}



@dataclass(frozen=True)
class SolverConfig:
    mode: str = "a"
    investigate_limit: int = 3
    # Switch to hail_mary when we've confirmed this many distinct letters
    threshold_known_letters: int = 4
    # Switch to hail_mary when this many positions are locked (green)
    threshold_locked_positions: int = 3
    # Switch to hail_mary when candidates fall at or below this count
    threshold_candidate_count: int = 15
    # Mode A only: use a separator guess from the full pool when hail_mary has
    # more than this many candidates (prevents sequential exhaustion of rhyme clusters).
    threshold_separator: int = 2
    # Mode C only: switch from entropy-pick to direct-candidate when at or below this count.
    threshold_direct: int = 2
    # Mode C only: when candidates > this, use full guess pool for entropy (broader search).
    # When candidates <= this, use candidates-only pool (fast + likely to solve directly).
    threshold_full_pool: int = 3


@dataclass(frozen=True)
class SolverRunResult:
    words_tried: list[str]
    turns_taken: int
    solved: bool
    mode_trace: list[str]


def _unique_letter_score(word: str, frequencies: dict[str, int]) -> int:
    seen = set()
    value = 0
    for char in word:
        if char not in seen:
            value += frequencies.get(char, 0)
            seen.add(char)
    return value


def _build_letter_frequencies(words: list[str]) -> dict[str, int]:
    counts: Counter[str] = Counter()
    for word in words:
        counts.update(set(word))
    return dict(counts)


def _select_investigate_guess(
    guess_words: list[str],
    tried: set[str],
    candidates: list[str],
    constraints: SolverConstraints | None = None,
) -> str:
    """Pick the best information-gathering guess from the full allowed-guess pool.

    Prefers words with all-unique letters. Strongly scores letters not yet
    confirmed, since already-known letters yield zero new information.
    """
    frequencies = _build_letter_frequencies(candidates)

    # Letters already known from previous guesses — contribute little new info.
    known_letters: set[str] = set()
    if constraints is not None:
        known_letters = (
            set(constraints.min_counts.keys()) | set(constraints.fixed_positions.values())
        )

    best_word = ""
    best_score = -1

    for word in guess_words:
        if word in tried:
            continue
        letters = set(word)
        # Large bonus for having all distinct letters; each duplicate dilutes value.
        score = len(letters) * 100
        for char in letters:
            freq = frequencies.get(char, 0)
            # Unknown letters deliver full information value; known ones are worth
            # a fraction since their presence is already confirmed.
            if char not in known_letters:
                score += freq * 2
            else:
                score += freq // 4
        if score > best_score:
            best_word = word
            best_score = score

    if best_word:
        return best_word

    # Fallback: return any untried guess word
    for word in guess_words:
        if word not in tried:
            return word
    raise RuntimeError("no valid investigate guess available")


def _select_separator_guess(
    guess_words: list[str],
    candidates: list[str],
    tried: set[str],
) -> str:
    """Pick a guess that tests the most variable letters across remaining candidates.

    Used in mode A when hail_mary mode still has many candidates. Searches the
    full guess pool so it can find words covering many variable positions at once.
    Gives a bonus to words that are themselves answer candidates.
    """
    candidate_set = set(candidates)
    frequencies = _build_letter_frequencies(candidates)

    # Letters that differ across candidate positions — the key information targets.
    variable_letters: set[str] = set()
    for pos in range(WORD_LENGTH):
        pos_letters = {word[pos] for word in candidates}
        if len(pos_letters) > 1:
            variable_letters.update(pos_letters)

    best_word = ""
    best_score = -1

    for word in guess_words:
        if word in tried:
            continue
        letters = set(word)
        covered_variable = letters & variable_letters
        # Primary: unique variable letters covered, weighted by candidate frequency.
        score = len(covered_variable) * 200
        for char in covered_variable:
            score += frequencies.get(char, 0)
        # Secondary: total unique letters (any extra info helps).
        score += len(letters) * 10
        # Bonus: the word is itself a candidate — it could solve directly.
        if word in candidate_set:
            score += 50
        if score > best_score:
            best_word = word
            best_score = score

    if best_word:
        return best_word
    return _select_hail_mary_guess(candidates, tried)


def _select_hail_mary_guess(candidates: list[str], tried: set[str]) -> str:
    """Pick the next untried candidate from the answer-eligible list."""
    for word in candidates:
        if word not in tried:
            return word
    raise RuntimeError("no candidate left for hail mary")


def _should_use_hail_mary(
    turn: int,
    constraints: SolverConstraints,
    candidate_count: int,
    config: SolverConfig,
) -> bool:
    """Return True when investigate phase should end and hail mary begin."""
    if config.mode == "b":
        return True
    # After 3 investigate turns the strategy always commits to hail mary.
    if turn >= config.investigate_limit:
        return True
    known_letters = len(constraints.min_counts)
    locked_positions = len(constraints.fixed_positions)
    return (
        known_letters >= config.threshold_known_letters
        or locked_positions >= config.threshold_locked_positions
        or candidate_count <= config.threshold_candidate_count
    )


def solve_secret(
    secret: str,
    guess_words: list[str],
    answer_words: list[str],
    config: SolverConfig | None = None,
) -> SolverRunResult:
    """Solve a Wordle puzzle.

    guess_words: full allowed-guess pool (used during investigate phase).
    answer_words: answer-eligible words only (used during hail_mary phase and
                  for tracking remaining candidates).
    """
    cfg = config or SolverConfig()
    if cfg.mode not in {"a", "b", "c"}:
        raise ValueError("solver mode must be 'a', 'b', or 'c'")

    if cfg.mode == "c":
        return _solve_mode_c(secret, guess_words, answer_words, cfg)

    constraints = SolverConstraints()
    tried: set[str] = set()
    words_tried: list[str] = []
    mode_trace: list[str] = []

    for turn in range(MAX_TURNS):
        candidates = [word for word in answer_words if constraints.candidate_matches(word)]
        if not candidates:
            break

        use_hail_mary = _should_use_hail_mary(turn, constraints, len(candidates), cfg)
        mode = "hail_mary" if use_hail_mary else "investigate"
        mode_trace.append(mode)

        if use_hail_mary:
            # Mode A: use a separator when too many candidates remain to guess
            # sequentially within the remaining turns budget.
            if cfg.mode == "a" and len(candidates) > cfg.threshold_separator:
                guess = _select_separator_guess(guess_words, candidates, tried)
            else:
                guess = _select_hail_mary_guess(candidates, tried)
        else:
            guess = _select_investigate_guess(guess_words, tried, candidates, constraints)

        tried.add(guess)
        words_tried.append(guess)
        score = score_guess(secret, guess)

        if all(value == 2 for value in score):
            return SolverRunResult(
                words_tried=words_tried,
                turns_taken=len(words_tried),
                solved=True,
                mode_trace=mode_trace,
            )

        constraints.update(guess, score)

    return SolverRunResult(
        words_tried=words_tried,
        turns_taken=len(words_tried),
        solved=False,
        mode_trace=mode_trace,
    )


# ── Mode C: entropy-driven with precomputed opener + turn-2 lookup ─────────────

def _pattern_int(guess: str, secret: str) -> int:
    """Encode a score_guess result as a base-3 integer (0–242)."""
    sc = score_guess(secret, guess)
    return sc[0] + 3 * sc[1] + 9 * sc[2] + 27 * sc[3] + 81 * sc[4]


def _entropy_guess(word: str, candidates: list[str]) -> float:
    """Shannon entropy of the partition induced by guessing `word` against `candidates`."""
    n = len(candidates)
    if n <= 1:
        return 0.0
    counts: Counter[int] = Counter()
    for secret in candidates:
        counts[_pattern_int(word, secret)] += 1
    h = 0.0
    for c in counts.values():
        p = c / n
        h -= p * log2(p)
    return h


def _best_entropy_guess(
    candidates: list[str], tried: set[str], pool: list[str] | None = None
) -> str:
    """Pick the word from pool (or candidates if pool is None) with highest entropy.

    When pool == candidates this is the pure candidate-only strategy (O(n^2)).
    When pool is the full guess list this finds better discriminators but is slower.
    """
    search_pool = pool if pool is not None else candidates
    candidate_set_for_bonus = set(candidates)
    best_word = candidates[0]
    best_h = -1.0
    n = len(candidates)
    for word in search_pool:
        if word in tried:
            continue
        h = _entropy_guess(word, candidates)
        # Tiny tie-breaker: prefer words that are themselves answer candidates.
        if word in candidate_set_for_bonus:
            h += 0.5 / max(n, 1)
        if h > best_h:
            best_h = h
            best_word = word
    return best_word


def _solve_mode_c(
    secret: str,
    guess_words: list[str],
    answer_words: list[str],
    cfg: SolverConfig,
) -> SolverRunResult:
    """Mode C: entropy-optimal solver.

    Turn 1: Fixed opener (MODE_C_OPENER = 'crate') — optimal for avg turns.
    Turn 2: Precomputed best word from full guess pool for each opener pattern.
    Turn 3+: If candidates ≤ threshold_direct, guess directly from candidates.
             Otherwise pick highest-entropy word from the answer candidates pool.

    This gives ~3.37 avg turns on the full answer set.
    """
    constraints = SolverConstraints()
    tried: set[str] = set()
    words_tried: list[str] = []
    mode_trace: list[str] = []

    opener_pattern: int | None = None  # recorded after turn 1
    turn2_pattern: int | None = None   # recorded after turn 2

    for turn in range(MAX_TURNS):
        candidates = [word for word in answer_words if constraints.candidate_matches(word)]
        if not candidates:
            break

        if turn == 0:
            guess = MODE_C_OPENER
            mode_trace.append("entropy_opener")
        elif turn == 1:
            # Use precomputed lookup; fall back to first candidate on miss.
            guess = MODE_C_TURN2.get(opener_pattern or 0, candidates[0])
            if guess in tried:
                guess = _best_entropy_guess(candidates, tried)
            mode_trace.append("entropy_lookup")
        elif turn == 2:
            # Use precomputed turn-3 lookup; fall back to full-pool entropy.
            if len(candidates) == 1:
                guess = candidates[0]
                mode_trace.append("direct")
            else:
                key = (opener_pattern or 0, turn2_pattern or 0)
                guess = MODE_C_TURN3.get(key, "")
                if not guess or guess in tried:
                    pool = guess_words if len(candidates) > cfg.threshold_full_pool else None
                    guess = _best_entropy_guess(candidates, tried, pool=pool)
                mode_trace.append("entropy_lookup")
        elif len(candidates) <= cfg.threshold_direct:
            guess = next((w for w in candidates if w not in tried), candidates[0])
            mode_trace.append("direct")
        else:
            # Use full guess pool when many candidates remain — broader search finds
            # better discriminators (e.g. breaks rhyme clusters like _atch/_ight).
            # Fall back to candidates-only pool when few remain (fast + likely solved).
            pool = guess_words if len(candidates) > cfg.threshold_full_pool else None
            guess = _best_entropy_guess(candidates, tried, pool=pool)
            mode_trace.append("entropy_candidates")

        tried.add(guess)
        words_tried.append(guess)
        sc = score_guess(secret, guess)

        if all(value == 2 for value in sc):
            return SolverRunResult(
                words_tried=words_tried,
                turns_taken=len(words_tried),
                solved=True,
                mode_trace=mode_trace,
            )

        if turn == 0:
            # Encode the opener score as pattern int for the turn-2 lookup.
            opener_pattern = sc[0] + 3 * sc[1] + 9 * sc[2] + 27 * sc[3] + 81 * sc[4]
        elif turn == 1:
            turn2_pattern = sc[0] + 3 * sc[1] + 9 * sc[2] + 27 * sc[3] + 81 * sc[4]

        constraints.update(guess, sc)

    return SolverRunResult(
        words_tried=words_tried,
        turns_taken=len(words_tried),
        solved=False,
        mode_trace=mode_trace,
    )
